jet_cs_dbt:
  outputs:
    dev:
      dbname: jet_db
      host: 192.168.2.12
      pass: admin
      port: 5432
      schema: dbt
      threads: 1
      type: postgres
      user: postgres
  target: dev